### ISSUE TITLE
截至17年底的艦R立繪

### ISSUE THREAD

**Issue by jason199506** [harukaxxxx/TechTreeMoe#10]
是的我又來了(°∀°)ノ
  
https://imgur.com/a/q218e

由上到下分別為：
企業-甜蜜聖誕
雷鳴
德梅因
duke of york-騎士之禮
degrass(同名，非同級)
克里夫蘭
west viriginia改
古鷹改
加古改
彭薩克拉改
香取改
馬裏蘭-换装-试验型改良舰装

**Comment by harukaxxxx** [comment]
love U
不過最近在全站重寫
所以更新可能會晚些唷( *・ω・)✄

**Comment by harukaxxxx** [comment]
DONE
