### ISSUE TITLE
死圖

### ISSUE THREAD

**Issue by BlackoAngel** [harukaxxxx/TechTreeMoe#15]
載下來的圖檔全部都死圖了

**Comment by harukaxxxx** [comment]
在巴哈有公告過了
> 網站正在大幅度調整
> 若出現找不到網頁或各種BUG還請諒解

現在還在努力找解決辦法
還請耐心等等σ(o'ω'o)

**Comment by harukaxxxx** [comment]
經過萬番努力終於修復了下載功能
目前已經能正常使用
若還有遇到BUG再麻煩了！！
