### ISSUE TITLE
游戏内不显示图标

### ISSUE THREAD

**Issue by shrimpa** [harukaxxxx/TechTreeMoe#16]
放入resmod文件夹后进入游戏游戏内没有舰船图标显示

**Comment by harukaxxxx** [comment]
在巴哈有公告過了

> 網站正在大幅度調整
> 若出現找不到網頁或各種BUG還請諒解

現在還在努力找解決辦法
還請耐心等等σ(o'ω'o)

**Comment by harukaxxxx** [comment]
經過萬番努力終於修復了下載功能
目前已經能正常使用
若還有遇到BUG再麻煩了！！
