### ISSUE TITLE
Asashio Kancolle request

### ISSUE THREAD

**Issue by tinefanforvettel** [harukaxxxx/TechTreeMoe#26]
Request for this one 
![dd_asashio_kai_ni_463_full](https://user-images.githubusercontent.com/20445117/39954786-08604e7e-55ef-11e8-9b46-755f41960ee0.png)
![67700313_p0_master1200](https://user-images.githubusercontent.com/20445117/39954789-25250fe0-55ef-11e8-97b6-9a8ba210f757.jpg)

**Comment by harukaxxxx** [comment]
Sorry for that Asashio class hasn't add into WOWS yet, right?
Which ship you used for Asashio skin?
If Asashio doesn't in WOWS, this request will be reject.

**Comment by jason199506** [comment]
it is in game though....new T8 premium IJN DD

**Comment by harukaxxxx** [comment]
Okay!!! Will be add soon!!!

**Comment by harukaxxxx** [comment]
updated

**Comment by tinefanforvettel** [comment]
![rr](https://user-images.githubusercontent.com/20445117/40344365-ac89a122-5dbe-11e8-96f7-b2bb759b41ce.jpg)
