### ISSUE TITLE
不能保存

### ISSUE THREAD

**Issue by pswdbz** [harukaxxxx/TechTreeMoe#27]
**錯誤描述 :**
手动保存自动保存都无效

**錯誤步驟 :**
定制好以后点保存,再载入会变回预设设定.而且下载也是预设

**螢幕截圖 :**
如果可以，附上錯誤的截圖（有 console log 更佳）。

**環境 :**

* OS: [Windows]
* Browser [IE. Chrome,Edge ]

**其他描述 :**
若有其他描述請填寫於此。

**Comment by harukaxxxx** [comment]
反覆測試發現移動到其他頁面再回來會導致保存資料載入不正常的問題

**Comment by pswdbz** [comment]
OK完美,可以用了

**Comment by harukaxxxx** [comment]
我不知道為什麼他自動修好了
我什麼都不知道！
