### ISSUE TITLE
艦c塔什干立繪

### ISSUE THREAD

**Issue by pswdbz** [harukaxxxx/TechTreeMoe#28]
塔什干
![_](https://user-images.githubusercontent.com/38472139/39956534-3a0c710c-5615-11e8-8763-772c58999494.png)
塔什干改
![_](https://user-images.githubusercontent.com/38472139/39956535-3d15565c-5615-11e8-86db-dbd9f0c430dc.png)

**Comment by harukaxxxx** [comment]
Added to next update
